---
- name: Test SSM connectivity
  hosts: consul_clients
  gather_facts: no
  connection: aws_ssm

  tasks:
    - name: Check uptime
      amazon.aws.aws_ssm:
        region: "{{ aws_region }}"
        instance_id: "{{ inventory_hostname }}"
        cmd: "uptime"

